Add Company chat member
supermetrolog/crmka pull request #103
Opened 2024-10-28 19:06 UTC by nknwns

2024-10-28 20:12 UTC, supermetrolog requested changes

2024-10-28 20:12 UTC, supermetrolog commented on models/Company.php
> +	private ?int $_objectsCount  = null;
Дичь 
Это нужно доставать одним запросом
Либо оставь как было, потому что то что здесь добавилось никак не влияет на кол-во запросов

2024-10-28 20:13 UTC, supermetrolog commented on models/Company.php
> +	private ?int $_objectsCount  = null;
Лучше тут вьюху сделать конечно 
И доставать эти значения в одном запросе 
Код будет чище гораздо 
И быстрее все будет работать гораздо

2024-10-28 21:37 UTC, nknwns commented on models/Company.php
> +	private ?int $_objectsCount  = null;
Я хз что я там накалякал, но что-то накалякал

2024-10-29 16:50 UTC, supermetrolog approved these changes

2024-10-29 16:52 UTC, merged