Event manager
supermetrolog/crmka pull request #123
Opened 2024-11-06 17:33 UTC by nknwns

2024-11-06 21:59 UTC, supermetrolog requested changes

2024-11-06 21:59 UTC, supermetrolog commented on services/ChatMemberSystemMessage/ChangeConsultantCompanyChatMemberSystemMessage.php
> +	}
Если вызвать валидацию до того как присвоили значения в свойства будет эксепшен

2024-11-06 21:59 UTC, supermetrolog commented on services/ChatMemberSystemMessage/ChatMemberSystemMessageInterface.php
Что то место расположения класса смущает 
Может ближе к логике с чатом его расположим?

2024-11-06 21:59 UTC, supermetrolog commented on services/ChatMemberSystemMessage/ChangeConsultantCompanyChatMemberSystemMessage.php
> +	}
Нужно дать свойствам дефолтные значения = null

2024-11-06 21:59 UTC, supermetrolog commented on usecases/ChatMember/ChatMemberMessageService.php
> +			'surveyIds'  => $dto->surveyIds
Напомни плз что за теги
И какое отношение список опросов имеет к сообщению в чате?

2024-11-06 21:59 UTC, supermetrolog commented on usecases/ChatMember/ChatMemberMessageService.php
> +			}
Такая же логика ниже 
Можно вынести в общий метод

2024-11-06 21:59 UTC, supermetrolog commented on usecases/ChatMember/ChatMemberMessageService.php
> +			$this->relationService->deleteByQuery($query);
Сходу не понять что происходит 
Чтобы было читабельней можно вынести это в метод и обозвать его
По названию будет понятно что происходит

2024-11-06 21:59 UTC, supermetrolog commented on listeners/ChangeConsultantCompanySystemChatMessageListener.php
> +			]));
Не понимаю, почему сервис для сообщений в чате занимается уведомлениями 
У нас вроде есть удобный билдер для уведомлений и скорее всего что-то что их отправляет

2024-11-06 21:59 UTC, supermetrolog commented on config/common/web/config.php
> +			'eventManager' => [
Думаю его нужно зарегистрировать в общем конфиге так как его можно использовать так же в консольном приложении

2024-11-06 21:59 UTC, supermetrolog commented on config/common/web/config.php
> +			'eventManager' => [
Плюс его лучше зарегистрировать в контейнере как синглтон 
А сюда отдавать уже из контейнера объект

2024-11-07 03:34 UTC, nknwns commented on components/EventManager.php
> +		Event::trigger(self::class, get_class($event), $event);
$event::class только с 8 версии
Первым аргументом
string $class – the fully qualified class name to which the event handler needs to attach

Я так и не понял до конца, что туда лучше передавать. Сам eventManager или event class например

2024-11-07 03:48 UTC, nknwns commented on usecases/ChatMember/ChatMemberMessageService.php
> +			'surveyIds'  => $dto->surveyIds
Ну тэги это уже давно в сообщениях, еще с их появления
А survey попросили иметь возможность прикреплять к сообщению. Мол вот в таком-то опросе можно что-то узнать/посмотреть

2024-11-07 04:44 UTC, nknwns commented on listeners/ChangeConsultantCompanySystemChatMessageListener.php
> +			]));
Потому что это notification который висит на сообщении, то есть это часть мессенджера. Внутри себя он отправлением notification и вяжет его с message. Хз, такой интерфейс от сервиса уже был и я его заюзал. Это не просто уведомление по сокету например, это именно уведомление на сообщении в чате

2024-11-08 16:39 UTC, supermetrolog requested changes

2024-11-08 16:39 UTC, supermetrolog commented on resources/ChatMemberMessage/ChatMemberMessageSurveyResource.php
> +class ChatMemberMessageSurveyResource extends JsonResource
Можно просто SurveyResource назвать же

2024-11-08 16:39 UTC, supermetrolog commented on config/common/web/url_rules.php
> +				'POST,OPTIONS system'                   => 'create-system',
Подскажи плз зачем это надо? 
Чет не логично, что системное сообщение создается не системой, а пользователем

2024-11-08 16:45 UTC, supermetrolog commented on listeners/ChangeConsultantCompanySystemChatMessageListener.php
> +			]));
Понял. Я забыл что у нас уведомления на сообщениях

2024-11-09 15:23 UTC, nknwns commented
1) Удалил эндпоинт для создания системного сообщения, ненужная хрень
2) Трекаю, есть ли в опроснике определенный вопрос. Если у него true ответ, то триггерю ивент. В нем уже отправляю системное сообщение в чат и задачу на него вешаю на модера.

2024-11-10 09:40 UTC, supermetrolog commented on components/EventManager.php
> +		Event::trigger(self::class, get_class($event), $event);
Одно и то же событие может быть инициировано разными классами
В событии есть поле sender (туда попадает объект, который инициировал событие)
Чтобы он туда попал, нужно его воткнуть вместо self::class 

Ну в общем то нам это скорее всего не пригодится, поэтому можно оставить как есть

2024-11-10 09:50 UTC, supermetrolog commented on helpers/HTMLHelper.php
> +class HTMLHelper
Честно говоря вообще не нравится то что бэк html-ем тут занимается
Откуда бэку знать, что на фронте html

Если нам нужно генерить разметку на бэке, нужно абстрагироваться от html
Можно использовать markdown и конверить его на фронте в html
Так например поступают в laravel

Ну это сейчас не обязательно. Если время найдется отрефачить, то лучше отрефачить

2024-11-10 10:00 UTC, supermetrolog commented on models/QuestionAnswer.php
> +	public const ANSWER_ID_WITH_DEVELOPMENT_COMPANY_EVENT = 3;
Это что айдишки? Если да, то это дичь

2024-11-10 10:00 UTC, supermetrolog commented on models/TaskTag.php
> +	public const SURVEY_TASK_TAG_ID = 5;
Тоже дичь

2024-11-10 16:46 UTC, supermetrolog commented on helpers/ArrayHelper.php
> +	}
Ну тут перемудрил мощно))
O(n) сделал, хотя массив или мапа позволяют доставать за O(1) элементы
Либо array_key_exists использовать можно либо же isset
Второй  вариант быстрее и предпочтительней, если нам пох на  NULL элементы

2024-11-10 16:59 UTC, supermetrolog commented on helpers/ArrayHelper.php
> +	}
А ну это я значит перемудрил мощно))
Но подход с таким поиском не очень на мой взгляд. Потому что этот метод покрываем только один уровень вложенности, ну и не супер читабельно в клиентском коде
Я бы сделал геттер типа effectKinds() и чекал бы просто  includes
Но коли мы торопимся и так норм

2024-11-10 17:00 UTC, supermetrolog commented on listeners/Survey/QuestionAnswerEffectListener.php
> +		/** @var Survey $survey */
А тут разве и так не понятно, что возвращает метод?

2024-11-10 17:04 UTC, nknwns commented on listeners/Survey/QuestionAnswerEffectListener.php
> +		/** @var Survey $survey */
Упс, не подчистил

2024-11-10 17:05 UTC, supermetrolog commented on listeners/Survey/QuestionAnswerEffectListener.php
> +				}
Вот это не очень хорошо
Сейчас оставим коли торопимся
Но тут нужен паттерн стратегия для обработки каждого kind
А вот событиями нельзя злоупотреблять
Потому что потом очень тяжело дебажить код который вызывает цепочку событий
Так что лучше вот это отрефачить потом

2024-11-10 17:11 UTC, supermetrolog commented on listeners/Survey/QuestionAnswerEffectListener.php
> +				$eventShouldBeTriggered = (bool)json_decode($answer->surveyQuestionAnswer->value);
json_decode может вернуть null если json не валидый
Каст null в bool = false
Соответственно тут бажок может быть
Я бы чекал результат на null

И в целом не особо понимаю, как json_decode можно кастануть в bool?
Результатом этой функции обычно является массив/мапа/объект

2024-11-10 17:14 UTC, supermetrolog commented on listeners/Survey/QuestionAnswerEffectListener.php
> +				$eventShouldBeTriggered = (bool)json_decode($answer->surveyQuestionAnswer->value);
Тут тоже самое

2024-11-10 17:20 UTC, supermetrolog commented on usecases/QuestionAnswer/QuestionAnswerService.php
> +
Теперь тут транзакция нужна уже

2024-11-10 17:20 UTC, supermetrolog commented on usecases/QuestionAnswer/QuestionAnswerService.php
> +
Тут тоже нужна транзакция

2024-11-10 18:03 UTC, supermetrolog approved these changes

2024-11-10 18:03 UTC, merged