Add mime_type for media
supermetrolog/crmka pull request #17
Opened 2024-06-09 23:47 UTC by StulE-ru

2024-06-10 05:15 UTC, supermetrolog requested changes
Чет не вижу где mime type выясняется и пишется в базу 
Я даже готовый кусок кода написал в таске, но его тут нет:)

2024-06-10 05:15 UTC, supermetrolog commented on migrations/m240609_232049_add_mime_type_column_in_media_table.php
> +			$this->string()->notNull()
Из-за not null упадет деплой 
Сделай по дефолту text/plain

2024-06-10 06:13 UTC, StulE-ru commented
> Чет не вижу где mime type выясняется и пишется в базу 
> Я даже готовый кусок кода написал в таске, но его тут нет:)

Посмотри
usecases/Media/CreateMediaService.php

2024-06-11 18:51 UTC, supermetrolog approved these changes

2024-06-11 18:52 UTC, merged