Endpoint: tasks/statuses-by-user
supermetrolog/crmka pull request #3
Opened 2024-05-21 21:02 UTC by StulE-ru

2024-05-21 21:04 UTC, supermetrolog commented on config/common/web/url_rules.php
> +				'GET,OPTIONS statuses-by-user/<user_id>'    => 'statuses-by-user',
Назовы эндпоинт /statistic 
UserId лучше убрать из path, а брать его из query так как может понадобиться общая статистика

2024-05-21 21:06 UTC, supermetrolog commented on controllers/TaskController.php
> +	public function actionStatusesByUser(int $user_id)
Переделать в соотсветствии с выше сказанным

2024-05-21 21:09 UTC, supermetrolog commented on models/Task.php
> +	public static function getStatusesByUser(int $user_id)
Такие штуки лучше не писать в моделях
Вынеси это в репозиторий

Плюс ты здесь делаешь 4 запроса. Можно сделать одним запросом. 
Плюс используешь andWhere чтобы найти не удаленные. 
Скорее всего уже есть обертка в active query типа notDeleted

2024-05-21 21:26 UTC, StulE-ru commented on config/common/web/url_rules.php
> +				'GET,OPTIONS statuses-by-user/<user_id>'    => 'statuses-by-user',
А я не могу его /statistic назвать, выдает ошибку "неправильный id" из-за того что есть эндпоин view /<id>, может /statistic/statuses назвать?

2024-05-21 21:29 UTC, supermetrolog commented on config/common/web/url_rules.php
> +				'GET,OPTIONS statuses-by-user/<user_id>'    => 'statuses-by-user',
Нет. Можно назвать statistic 
Забудь про статусы. Туда кроме статусов в будущем еще можно запихнуть что-нибудь) 
Возможно ты не убрал из экшена в аргументе user id

2024-05-21 21:31 UTC, StulE-ru commented on config/common/web/url_rules.php
> +				'GET,OPTIONS statuses-by-user/<user_id>'    => 'statuses-by-user',
![image](https://github.com/supermetrolog/crmka/assets/58220335/e02eb465-0f98-456a-84ad-8c5516251934)
![image](https://github.com/supermetrolog/crmka/assets/58220335/b47ebbfe-4577-4a0c-985b-64642428ba93)

2024-05-21 21:33 UTC, supermetrolog commented on config/common/web/url_rules.php
> +				'GET,OPTIONS statuses-by-user/<user_id>'    => 'statuses-by-user',
Убери слеш перед statistic

2024-05-21 21:36 UTC, supermetrolog commented on config/common/web/url_rules.php
> +				'GET,OPTIONS statuses-by-user/<user_id>'    => 'statuses-by-user',
Поменяй местами statistic и view
Statistic перетащи перед view

2024-05-21 22:09 UTC, StulE-ru commented on models/Task.php
> +	public static function getStatusesByUser(int $user_id)
Переделал

2024-05-21 22:09 UTC, StulE-ru commented on controllers/TaskController.php
> +	public function actionStatusesByUser(int $user_id)
Переделал

2024-05-22 20:12 UTC, supermetrolog requested changes

2024-05-22 20:18 UTC, supermetrolog requested changes

2024-05-22 20:18 UTC, supermetrolog commented on controllers/TaskController.php
> +		return $this->repository->getStatusStatisticByUserId($this->user->id);
User id нужно брать из реквеста а не текущего юзера 
Плюс user id не обязательный фильтр
То есть должно без него работать, если его не прислали
В репозитории можешь использовать andFilterWhere

2024-05-22 20:18 UTC, supermetrolog commented on repositories/TaskRepository.php
> +					Task::find()->select('COUNT(*)')->where(['user_id' => $user_id])->byStatus(Task::STATUS_IMPOSSIBLE)->notDeleted(), true
User id не обязательный фильтр, как описал выше

2024-05-22 20:57 UTC, supermetrolog approved these changes

2024-05-22 20:57 UTC, merged