[#346] Task features
supermetrolog/crmka pull request #66
Opened 2024-09-01 19:26 UTC by nknwns

Добавлены модели:
1. TaskObserver
2. TaskComment

Добавлены следующие эндпоинты:
1. GET /tasks/:id/comments - список всех комментариев у задачи
2. POST /tasks/:id/comments - создать комментарий к задаче
3. GET /task-tags/all - список всех тегов, даже удаленных для пользователей
4. POST /tasks/:id/read - отметить задачу прочитанной для TaskObserver
5. GET /tasks/counts - статистика. Список количества задач по разным status
6. GET /tasks/relations - статистика. Список количества задач по разным типам связей пользователя к задаче

Добавлены следующие ресурсы:
1. TaskCommentResource
2. TaskWithRelationResource - задача с related_by и last_comment. Для просмотра в карточке задачи
3. ChatMemberMessageShortResource - сообщение с минимумом информации. Без задач, уведомлений и т.д
4. TaskObserverResource

2024-09-02 18:45 UTC, supermetrolog commented on controllers/TaskController.php
> +		$task->refresh();
Это внутри сервиса можно сделать. Надо сделать сервис "декоратор", который будет менять статус и коммент сохранять

2024-09-02 18:47 UTC, supermetrolog commented on controllers/TaskController.php
> +		$this->taskObserverRepository = $taskObserverRepository;
nitpick: Почему все до конструктора, а это после?)

2024-09-02 18:48 UTC, supermetrolog commented on controllers/TaskController.php
> +	 * @throws Exception|Throwable
nitpick: можно просто Throwable

2024-09-02 18:49 UTC, supermetrolog commented on controllers/TaskController.php
> +		$form->setScenario(TaskCommentForm::SCENARIO_UPDATE);
action -> create
scenario -> update
Что-то не то

2024-09-02 19:01 UTC, supermetrolog commented on models/Task.php
> +		return $this->hasMany(TaskTaskTag::class, ['task_id' => 'id'])->andWhere([self::SOFT_DELETE_ATTRIBUTE => null]);
Здесь можно вызывать notDeleted  у TastTaskTagQuery
Чтобы работали типы можно указать его пхп доком
/* @var TastTaskTagQuery $query */
$query = $this->hasMany(TaskTaskTag::class, ['task_id' => 'id']);
$query->notDeleted();

return $query;

2024-09-02 19:04 UTC, supermetrolog commented on models/forms/Task/TaskChangeStatusForm.php
>  			[['status'], 'in', 'range' => [Task::STATUS_DONE, Task::STATUS_ACCEPTED, Task::STATUS_IMPOSSIBLE]],
Лучше сделать статический метод Task::getStatuses();

2024-09-02 19:11 UTC, supermetrolog commented on repositories/TaskObserverRepository.php
> +	public function findModelByTaskIdAndUserId(int $taskId, int $userId): ?TaskObserver
nitpick: findOne обычно в yii принято писать

2024-09-02 19:14 UTC, supermetrolog commented on repositories/TaskCommentRepository.php
> +	public function findModelsByTaskId(int $id): array
nitpicK: Можно просто findByTaskId
Просто вот эта разница в одну букву в  model или models не особо играет потому что это тяжело прочитать
Если прям хочешь выделить чтоб из названия было понятно, то лучше findOne и findAll использовать

2024-09-02 19:18 UTC, supermetrolog commented on repositories/TaskRepository.php
> +	public function getCountsByUserIdOrCreatedById(?int $user_id = null, ?int $created_by_id = null)
Возвращаемый тип не указан

2024-09-02 19:19 UTC, supermetrolog commented on repositories/TaskRepository.php
> +		])->filterWhere(['or', ['user_id' => $user_id], ['created_by_id' => $created_by_id]])->notDeleted()->asArray()->all()[0];
all()[0] выглядит стремно
Просто one() не работает?
А что будет если ни одной строки подходящей по условию не будет?

2024-09-02 19:21 UTC, supermetrolog commented on repositories/TaskRepository.php
> +	public function getCountsByUserIdOrCreatedById(?int $user_id = null, ?int $created_by_id = null)
Плюс массив возвращать так себе так без понятия что там внутри
Лучше сделать dto и замапить туда результат
Но можно сделать так чтобы orm сама это сделала
Можно сделать модель (вьюха) которая наследуется от Task и имеет свои поля all, created, accepted ... 
И делая запрос через нее, в эти поля замапится результат

2024-09-02 19:23 UTC, supermetrolog commented on repositories/TaskRepository.php
> +	public function getCountsByObserverIdAndByUserIdOrCreatedById(?int $user_id = null, ?int $created_by_id = null, ?int $observer_id = null)
and by and by or by 
Можно сделать билдер прям для этого запроса и красиво настраивать его без вот этой мишуры
Но ты пока не потянешь так как негде подсмотреть реализацию, так что это на будущее тебе коммент)

2024-09-02 19:24 UTC, supermetrolog commented on repositories/TaskRepository.php
> +	public function getCountsByObserverIdAndByUserIdOrCreatedById(?int $user_id = null, ?int $created_by_id = null, ?int $observer_id = null)
И типа нет снова
Тут тоже нужно вьюху использовать, а не массив отдавать

2024-09-02 19:25 UTC, supermetrolog commented on repositories/TaskRepository.php
> +		return $query->asArray()->all()[0];
Та же проблема что выше

2024-09-02 19:28 UTC, supermetrolog commented on repositories/TaskRepository.php
> +		$query->leftJoin(TaskObserver::tableName(), TaskObserver::getColumn('task_id') . ' = ' . Task::getColumn('id'));
join with можно использовать, а не сырой join 
До этого тоже встречал, там тоже можно поправить

Плюс здесь после джойна, если связь не один к одному нужна группировка чтобы правильно посчитать сумму и прочее

groupBy([task.id])

2024-09-02 19:31 UTC, supermetrolog commented on repositories/TaskRepository.php
> +	public function getRelationsStatisticByUserId(int $user_id)
То же самое что выше описывал

2024-09-02 19:32 UTC, supermetrolog commented on repositories/TaskRepository.php
> +		return $query->asArray()->all()[0];
То же самое что выше

2024-09-02 19:32 UTC, supermetrolog commented on repositories/TaskRepository.php
> +		$query->leftJoin(TaskObserver::tableName(), TaskObserver::getColumn('task_id') . ' = ' . Task::getColumn('id'));
То же самое что выше

2024-09-02 19:37 UTC, supermetrolog commented on usecases/TaskObserver/TaskObserverService.php
> +//		return $alert;
nitpick: можно удалить раз не надо

2024-09-02 19:39 UTC, supermetrolog requested changes
гитхаб просит оставить тут коммент

2024-09-03 03:25 UTC, nknwns commented on controllers/TaskController.php
> +		$task->refresh();
Создал сервис `changeTaskStatusService`, внутрь которого инкапсулировал `taskService` и `createTaskCommentService`. В `TaskChangeStatusForm` добавил `changed_by_id` - ид юзера, который меняет статус. В `ChangeTaskStatusDto` тоже добавил `changed_by_id`.

2024-09-03 03:33 UTC, nknwns commented on models/forms/Task/TaskChangeStatusForm.php
>  			[['status'], 'in', 'range' => [Task::STATUS_DONE, Task::STATUS_ACCEPTED, Task::STATUS_IMPOSSIBLE]],
Создал `statis getEditableStatuses()`, commit 2b4ad76daa6bddb8f63fc57fb2aaa48126500443

2024-09-03 03:43 UTC, nknwns commented on controllers/TaskController.php
> +		$this->taskObserverRepository = $taskObserverRepository;
Fixed
Reference: c10cce201496abc245b46f2c9f90dd8373c5ea33

2024-09-03 04:04 UTC, nknwns commented on controllers/TaskController.php
> +		$form->setScenario(TaskCommentForm::SCENARIO_UPDATE);
Fixed
Reference: b900b210456e8023eb0b775976050e948c241141

2024-09-03 04:04 UTC, nknwns commented on controllers/TaskController.php
> +	 * @throws Exception|Throwable
Fixed
Reference: b900b210456e8023eb0b775976050e948c241141

2024-09-03 04:04 UTC, nknwns commented on models/Task.php
> +		return $this->hasMany(TaskTaskTag::class, ['task_id' => 'id'])->andWhere([self::SOFT_DELETE_ATTRIBUTE => null]);
Fixed
Reference: b900b210456e8023eb0b775976050e948c241141

2024-09-03 04:04 UTC, nknwns commented on repositories/TaskObserverRepository.php
> +	public function findModelByTaskIdAndUserId(int $taskId, int $userId): ?TaskObserver
Fixed
Reference: b900b210456e8023eb0b775976050e948c241141

2024-09-03 04:05 UTC, nknwns commented on repositories/TaskCommentRepository.php
> +	public function findModelsByTaskId(int $id): array
Fixed
Reference: b900b210456e8023eb0b775976050e948c241141

2024-09-03 04:05 UTC, nknwns commented on usecases/TaskObserver/TaskObserverService.php
> +//		return $alert;
Fixed
Reference: b900b210456e8023eb0b775976050e948c241141

2024-09-03 18:43 UTC, nknwns commented on repositories/TaskRepository.php
> +	public function getCountsByUserIdOrCreatedById(?int $user_id = null, ?int $created_by_id = null)
Fixed
Reference: 407baacbdf58a6358ec4f02f5681ae85db6b6607

2024-09-03 18:44 UTC, nknwns commented on repositories/TaskRepository.php
> +	public function getCountsByObserverIdAndByUserIdOrCreatedById(?int $user_id = null, ?int $created_by_id = null, ?int $observer_id = null)
Если у тебя есть пример на чьем-то гите или статья, буду рад почитать)

2024-09-03 18:45 UTC, nknwns commented on repositories/TaskRepository.php
> +		])->filterWhere(['or', ['user_id' => $user_id], ['created_by_id' => $created_by_id]])->notDeleted()->asArray()->all()[0];
Fixed
Reference:  407baacbdf58a6358ec4f02f5681ae85db6b6607

2024-09-03 18:45 UTC, nknwns commented on repositories/TaskRepository.php
> +		return $query->asArray()->all()[0];
Fixed
Reference: 407baacbdf58a6358ec4f02f5681ae85db6b6607

2024-09-03 18:46 UTC, nknwns commented on repositories/TaskRepository.php
> +		$query->leftJoin(TaskObserver::tableName(), TaskObserver::getColumn('task_id') . ' = ' . Task::getColumn('id'));
Fixed
Reference: 407baacbdf58a6358ec4f02f5681ae85db6b6607

2024-09-03 18:46 UTC, nknwns commented on repositories/TaskRepository.php
> +	public function getRelationsStatisticByUserId(int $user_id)
Fixed
Reference: 407baacbdf58a6358ec4f02f5681ae85db6b6607

2024-09-03 18:46 UTC, nknwns commented on repositories/TaskRepository.php
> +		return $query->asArray()->all()[0];
Fixed
Reference: 407baacbdf58a6358ec4f02f5681ae85db6b6607

2024-09-03 18:46 UTC, nknwns commented on repositories/TaskRepository.php
> +		$query->leftJoin(TaskObserver::tableName(), TaskObserver::getColumn('task_id') . ' = ' . Task::getColumn('id'));
Fixed
Reference: 407baacbdf58a6358ec4f02f5681ae85db6b6607

2024-09-03 18:48 UTC, nknwns commented
Замечания исправлены (наверное)

2024-09-03 19:06 UTC, supermetrolog commented on models/Task.php
> +		return $this->hasMany(TaskObserver::class, ['task_id' => 'id'])->andFilterWhere(['not', [TaskObserver::field('user_id') => $this->user_id]]);
Зачем здесь filter? andWhere было верным решением.
А вообще шо то шо то фигня
Связь по двум полям можно просто описать
['task_id' => 'id', 'user_id' => 'user_id']

2024-09-03 19:17 UTC, supermetrolog commented on models/views/TaskRelationStatisticView.php
> +}
Это что такое и почему оно тут?

2024-09-03 19:18 UTC, supermetrolog commented on models/views/TaskStatusStatisticView.php
> +}
Зачем это тут?
Плюс у тебя связи какие-то перегруженные. Какие-то сложны запросы в связях
Связи должны быть в идеале простые, а уже доп условия можно внутри репозитория делать или в крайнем случае внутри сервиса

2024-09-03 19:22 UTC, nknwns commented on models/views/TaskRelationStatisticView.php
> +}
Описал выше проблему

2024-09-03 19:22 UTC, nknwns commented on models/views/TaskStatusStatisticView.php
> +}
Описал выше проблему

2024-09-03 19:24 UTC, supermetrolog commented on usecases/Task/ChangeTaskStatusService.php
> +			return new SuccessResponse();
Сервис ничего не должен знать о респонсах
Посмотри откуда это импортируется
use app\kernel\web\http\responses\SuccessResponse;
Сервис не должен зависеть от http

2024-09-03 19:25 UTC, supermetrolog requested changes
Оставил комменты

2024-09-03 19:30 UTC, supermetrolog commented on models/Task.php
> +		return $this->hasMany(TaskObserver::class, ['task_id' => 'id'])->andFilterWhere(['not', [TaskObserver::field('user_id') => $this->user_id]]);
Да выводи просто текущего юзера тоже в списках обсервера. Это не проблема. Вон на гитлабе только что глянул в список ревьюверов самого себя можно включать на свою пр, что бессмысленно в большинстве своем. Но это не проблема. Можно просто не усложнять себе жизнь

2024-09-03 19:31 UTC, nknwns commented on usecases/Task/ChangeTaskStatusService.php
> +			return new SuccessResponse();
Упс, копировал из контроллера сервисы и прихватил случайно
Исправлено
Reference: 54f0b11fe8afcf74654bfc4ec0215b180c7b2853

2024-09-03 19:31 UTC, supermetrolog commented on models/views/TaskRelationStatisticView.php
> +}
Не ну проблему я понял, но зачем это во вьюху выносить? Тут все равно используются поля из главной модели Task. Внутри Task это можно описать если так надо

2024-09-03 22:00 UTC, nknwns commented on models/Task.php
> +		return $this->hasMany(TaskObserver::class, ['task_id' => 'id'])->andFilterWhere(['not', [TaskObserver::field('user_id') => $this->user_id]]);
Исправил
Reference: 768185ca11a0004e1edb2d525abda0eca0f33a69

2024-09-03 22:00 UTC, nknwns commented on models/views/TaskRelationStatisticView.php
> +}
Удалил ненужный метод, поставил условия в репозитории
Reference: 768185ca11a0004e1edb2d525abda0eca0f33a69

2024-09-03 22:01 UTC, nknwns commented
Убрал ненужные методы из вьюх, исправил TaskSearch

2024-09-04 04:12 UTC, supermetrolog approved these changes

2024-09-04 04:12 UTC, merged