Feature/media
supermetrolog/crmka pull request #7
Opened 2024-05-25 12:35 UTC by StulE-ru

2024-05-25 18:05 UTC, supermetrolog requested changes

2024-05-25 18:05 UTC, supermetrolog commented on usecases/Media/MediaService.php
> +		\Yii::$app->media->delete(basename($media->path));
В конструктор можно получать

2024-05-25 18:05 UTC, supermetrolog commented on components/MediaService.php
> +class MediaService extends Component
Просто Media можно назвать. Это ж не сервис, а компонент

2024-05-25 18:05 UTC, supermetrolog commented on components/MediaService.php
> +		$config['diskPath'] = rtrim($config['diskPath'], '\\/');
Зачем тут к ним обращаться если их значения будут лежать в свойствах после вызовы родительского конструктора? 
После этого можно уже обработать значения без работы с массивом вовсе

2024-05-25 18:05 UTC, supermetrolog commented on components/MediaService.php
> +		return $this->webPath . '/' . trim($filename, '\\/');
Сделай отдельный класс PathBuilder и собирай через него весь путь
Будет удобно

2024-05-26 00:11 UTC, StulE-ru commented on usecases/Media/MediaService.php
> +		\Yii::$app->media->delete(basename($media->path));
не понял

2024-05-26 01:16 UTC, supermetrolog requested changes

2024-05-26 01:16 UTC, supermetrolog commented on components/Media.php
> +		dd($this->pathBuilder->disk($path, $name, $extension));
Упс

2024-05-26 01:16 UTC, supermetrolog commented on components/Media.php
> +	public function put(string $path, string $name, string $extension, UploadedFile $uploadedFile): void
А зачем тут extension? Его нет внутри uploaded file?

2024-05-26 01:16 UTC, supermetrolog commented on components/MediaPathBuilder.php
Это вообще странная вещь
Я просил сделать pathBuilder а не mediaPathBuilder 
Нужно было сделать обычный билдер с методом типа join(string path)

Ну и метод build возвращал бы готовую строку 
Можно тот же trim туда тоже внедрить вызвав метод withTrim например 
Абстрагируйся от медиа и сделай просто билдер путей и потом используй его в медиа

2024-05-26 01:16 UTC, supermetrolog commented on config/common/common/components.php
> +	'media'       => fn() => Yii::$container->get('media'),
Не надо это регистрировать как компонент 
Это достаточно зарегистрировать в контейнере и получать потом в конструкторе 
Почитай про di контейнеры в целом

2024-05-26 01:16 UTC, supermetrolog commented on config/common/common/components.php
> +	'mediaPath'   => fn() => Yii::$container->get('mediaPath'),
От этого вообще нужно избавиться

2024-05-26 01:16 UTC, supermetrolog commented on config/common/common/container.php
> +		'media'                             => \app\components\Media::class,
Надо вот этот компонент настроить, а не mediaPath
MediaPath вообще удали

2024-05-26 01:16 UTC, supermetrolog commented on resources/MediaResource.php
> +			'web_path'      => \Yii::$app->mediaPath->web(
Все что тут ты собираешь уже должно находиться в path
То есть при сохранение надо собрать этот путь сохранить в базу 
То есть web path здесь не нужен а достаточно просто path отдавать

2024-05-26 01:16 UTC, supermetrolog commented on usecases/Media/CreateMediaService.php
> +			$this->media->put($dto->path, $name, $dto->uploadedFile->extension, $dto->uploadedFile);
Перемести это ниже 
Сначала save потом put

2024-05-26 01:16 UTC, supermetrolog commented on usecases/Media/CreateMediaService.php
> +			$this->media->put($dto->path, $name, $dto->uploadedFile->extension, $dto->uploadedFile);
Extension уже есть в uploadedfile зачем тогда его отдельно передавать?

2024-05-26 06:36 UTC, StulE-ru commented on components/Media.php
> +	public function put(string $path, string $name, string $extension, UploadedFile $uploadedFile): void
А если будет какая-то конвертация в будущем из png в условный jpg, надо будет изменять uploadedFile, а сейчас он используется чисто для сохранения временного файла

2024-05-26 06:43 UTC, StulE-ru commented on resources/MediaResource.php
> +			'web_path'      => \Yii::$app->mediaPath->web(
Не достаточно, ты же сам сказал, что в path хранить avatars/avatar.png, когда полный путь storage/avatars/avatar.png, это для того, чтобы потом можно было заменить storage и не трогать бд

2024-05-26 19:27 UTC, supermetrolog requested changes

2024-05-26 19:27 UTC, supermetrolog commented on components/Media.php
> +	public function pathBuilder(): PathBuilder
Вряд ли это тут надо возвращать

2024-05-26 19:27 UTC, supermetrolog commented on components/PathBuilder.php
Получился вообще не билдер а непонятно что. Это можно хоть в статический метод выносить так как тут состояния даже нет
Погугли плз что такое билдер и как его делать
Пока оставь это так. Пофиг. Потом переделаем. Пока нет времени

2024-05-26 19:27 UTC, supermetrolog commented on resources/MediaResource.php
> +			'path'          => $this->media->webPath($this->resource->path),
Здесь просто $this-resource-path напиши плз

2024-05-26 19:27 UTC, supermetrolog commented on usecases/Media/CreateMediaService.php
> +			$path = $this->media->pathBuilder()->join($dto->path, "{$name}.{$dto->uploadedFile->extension}");
Просто получи в конструкторе этот билдер отдельно. Нет смысла его доставать из какого-то другого класса так как это самодостаточный класс, который может быть использован сам по себе

2024-05-26 19:27 UTC, supermetrolog commented on usecases/Media/MediaService.php
> +		$media->delete();
Оберни плз в транзакци и сначала удали из базы, а потом удали из хранилища файлов по аналогии с созданием

2024-05-27 20:55 UTC, supermetrolog approved these changes

2024-05-27 20:55 UTC, merged