Chat member improvements #1
supermetrolog/crmka pull request #70
Opened 2024-09-10 17:06 UTC by nknwns

1) getUser теперь возвращает любого юзера по ID, а не только активного (иначе у нас нет возможности просматривать на фронте архивных юзеров, а такая возможность нужна).
2) ChatMemberSearch теперь работает с `model_type` = `user`.  Добавлен фильтр `status`, чтобы искать диалоги или только активных юзеров или диалоги архивных.
3) Добавил `created_at` для ObjectShortResource, `updated_at` теперь выдает `created_at`, если `last_update` не существует (то ли просто данные плохие в базе старой, то ли так задумали изначально. Но как будто я везде замечал, что updated_at всегда не равен null, что даже если не обновляли, то дата создания).
4) Добавил сортировку по `call`, `message`, `task`, `notification`. `call` сортирует по дате устаревания (дата последнего звонка, дата обновления, дата создания), `task` сортирует по дате добавления непрочитанной задачи, `notification` по дате последнего непрочитанного уведомления, `message` по дате последнего непрочитанного сообщения. `default` сортирует так же, как это изначально было в orderBy - по дате последнего события в чате или по дате последнего сообщения.

2024-09-10 18:07 UTC, supermetrolog requested changes

2024-09-10 18:07 UTC, supermetrolog commented on models/search/ChatMemberSearch.php
> +								. ', ' . Objects::field('publ_time') . ') ASC')
Сделай плз билдер для этой штуки, а то это выглядит отвратительно и в этом легко оставить бажок.
Билдер можно будет переиспользовать много раз.
Вот примерный вид клиентского кода с этим билдером:

IfExpressionBuilder::new()
->condition('last_update')
->left('last_update')
->right('publ_time')
->option(fn (string $expression) => $expression . ' ASC')
->build() 

Сделаем множество таких билдеров и потом их можно вынести в один билдер большой ExpressionBuilder

2024-09-11 04:09 UTC, nknwns commented on models/search/ChatMemberSearch.php
> +								. ', ' . Objects::field('publ_time') . ') ASC')
Сделано
Reference: 2d8bdace32c7db728150286a6149c795b2166f9d

2024-09-11 21:01 UTC, supermetrolog requested changes

2024-09-12 07:30 UTC, nknwns commented on repositories/ChatMemberRepository.php
> +			                                          'outdated_call_count'       => $this->makeNeedingCallCountQuery($model_types)
Ну ток так решил. Там в одном подзапросе сразу вычисление нужного количества (оно одинаковое для всех записей всегда и везде, его надо ток один раз посчитать и все).

2024-09-12 07:53 UTC, nknwns commented on repositories/ChatMemberRepository.php
> +		$model_types     = ArrayHelper::isArray($model_types) ? $model_types : [$model_types];
Reference: a5afac72a68ee62cc627135da6f3e687baf2e368

2024-09-12 07:55 UTC, nknwns commented on repositories/ChatMemberRepository.php
Reference: 9993ac131aa5ac86701a9ca3a2168185860fe5ed

2024-09-12 08:07 UTC, nknwns commented on models/search/ChatMemberSearch.php
> +			           'observer.task_id'   => new Expression(Task::field('id')),
Reference: 711cfc1f7ac8ee9984c82ef628c6fc7310084ad9

2024-09-12 09:43 UTC, nknwns commented on models/ActiveQuery/ChatMemberQuery.php
> +		$interval = 'DATE_SUB(NOW(), INTERVAL 1 YEAR)';
Reference: 3621e0a6015bcf242488e39a58a8f9d3e19b8e35

2024-09-12 09:55 UTC, nknwns commented on components/ExpressionBuilder/IfExpressionBuilder.php
> +	}
Они по умолчанию стоят 1 и 0. Я хз как их валидировать, только если на длину символов. Потому что тот же `null` туда можно установить, чтобы добиться условия `IF(object.message_id, object.id, null)`
Если сделать `IfExpressionBuilder::create()->condition('object.message_id')->build`, то будет `IF(object.message_id, 1, 0)`

2024-09-12 09:59 UTC, nknwns commented on components/ExpressionBuilder/IfExpressionBuilder.php
> +		return new Expression("IF($this->condition, $this->trueExpression, $this->falseExpression)");
Для этого и создал этот метод, чтобы получать чистое выражение без применения transform, alias и возможных будущих штук, пока нет кейса использования, но может появится))

Может вообще удалить этот метод из-за ненадобности, хз
Это была задумка, что можно создать билдер где-то, и от него взять как чистый IF куда-то вставить, так и через build() создать полное выражение вниз запроса или еще куда-то.. Чтобы не создавать таком кейсе два раза билдер, который будет почти одинаковым

2024-09-12 10:10 UTC, nknwns commented on components/ExpressionBuilder/ExpressionBuilder.php
> +	public function toString(): string
Надеюсь я правильно тебя понял
Reference: 5e351b5b2bff995fda6d03a67870a2d52e718bbf

2024-09-12 10:11 UTC, nknwns commented on components/ExpressionBuilder/IfExpressionBuilder.php
Эти?
Reference: 5e351b5b2bff995fda6d03a67870a2d52e718bbf

2024-09-12 10:13 UTC, nknwns commented on components/ExpressionBuilder/CompareExpressionBuilder.php
> +		return new Expression("$this->leftExpression $this->operator $this->rightExpression");
Жаль этого добряка..
Reference: a370855ac73b110da826b5f4008eac05902956ad

2024-09-12 10:13 UTC, nknwns commented on components/ExpressionBuilder/CompareExpressionBuilder.php
> +	public function lowerOrEqual(): self
Удалено
Reference: a370855ac73b110da826b5f4008eac05902956ad

2024-09-12 10:14 UTC, nknwns commented on components/ExpressionBuilder/CompareExpressionBuilder.php
Жаль этого добряка
Reference: a370855ac73b110da826b5f4008eac05902956ad

2024-09-12 19:31 UTC, supermetrolog commented on repositories/ChatMemberRepository.php
> +			                                          'outdated_call_count'       => $this->makeNeedingCallCountQuery($model_types)
Подзапрос в селект выполняется для каждой строки в результате выборки

2024-09-12 19:33 UTC, supermetrolog approved these changes

2024-09-12 19:36 UTC, supermetrolog commented on components/ExpressionBuilder/IfExpressionBuilder.php
> +	}
А если я туда null засуну? 
Вообще инициализация 1 и 0 это не логично и это неожиданное поведение 
Я не устанавливал значение а оно уже есть и почему то 1 и 0
Сделай плз так чтобы по умолчанию значения были null 
И в валидации можно чекать установили эти значения или нет 
Они всегда должны быть установлены 
И кейс когда мы намерено сунули null тоже решится

2024-09-12 19:56 UTC, nknwns commented on components/ExpressionBuilder/IfExpressionBuilder.php
> +	}
Добавил побольше валидации
Reference: 21c6b71ac01697d4e4bb8cf70a2886d5d5d9ebc4

2024-09-12 19:58 UTC, supermetrolog approved these changes

2024-09-12 19:58 UTC, merged