[#386] Automatically mark task as viewed if status is changed to completed
supermetrolog/crmka pull request #79
Opened 2024-09-20 13:06 UTC by nknwns

2024-09-20 13:09 UTC, nknwns commented
![](https://github.trello.services/images/mini-trello-icon.png) [Отмечать задачи прочитанными, если они выполнены](https://trello.com/c/yR8SQjxm/386-%D0%BE%D1%82%D0%BC%D0%B5%D1%87%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D1%87%D0%B8-%D0%BF%D1%80%D0%BE%D1%87%D0%B8%D1%82%D0%B0%D0%BD%D0%BD%D1%8B%D0%BC%D0%B8-%D0%B5%D1%81%D0%BB%D0%B8-%D0%BE%D0%BD%D0%B8-%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D1%8B)

2024-09-22 14:15 UTC, supermetrolog requested changes

2024-09-22 14:15 UTC, supermetrolog commented on models/TaskObserver.php
> +	public static function isViewed(TaskObserver $observer): bool
Почему эти методы статические?

2024-09-22 16:37 UTC, nknwns commented on models/TaskObserver.php
> +	public static function isViewed(TaskObserver $observer): bool
Изменил
Reference: 40e8c5a1a4e9c33505a0df559b24fd0258b9097f

2024-09-22 16:38 UTC, supermetrolog approved these changes

2024-09-22 16:38 UTC, merged