[#333] Multiple login
supermetrolog/crmka pull request #84
Opened 2024-10-01 20:26 UTC by nknwns

1. Создана таблица с токенами авторизации для юзеров. Юзер может авторизовываться с разных устройств (в том числе в таблице содержится инфа об ip и устройстве (браузере). Это для таблицы с залогиненными устройствами на фронте. Сотрудник сможет посмотреть, где он залогинен, и разлогинить любой свой клиент (а администратор может принудительно разлогинить все сессии сотрудника, если что-то случилось).
2. DateInterval helper (для удобного создания простых интервалов), Token helper (для парсинга Bearer в нормальный вид)
3. Рефакторинг `UserController` (созданы необходимые сервисы, dto, формы). В дальнейшем если проблем с текущей реализацией не будет, можно будет удалить все эти `User::createUser()` вообще из класса модели.
4. Создан `AuthenticationService` для авторизации и разлогина (с помощью него происходит `authenticate()` и `logout()`.
5. В `User` немного изменена имплементация для `Identity` для корректной выборки юзера по `access_token`.

2024-10-01 20:33 UTC, nknwns commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать множественные токены авторизации](https://trello.com/c/5bdWsONj/333-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%BC%D0%BD%D0%BE%D0%B6%D0%B5%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5-%D1%82%D0%BE%D0%BA%D0%B5%D0%BD%D1%8B-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8)

2024-10-01 21:30 UTC, supermetrolog requested changes

2024-10-01 21:30 UTC, supermetrolog commented on migrations/m240930_162744_create_user_access_token_table.php
> +			'user_id'      => $this->integer()->notNull(),
На него нужен индекс

2024-10-01 21:30 UTC, supermetrolog commented on models/ActiveQuery/UserAccessTokenQuery.php
> +			['>', $this->field('expires_at'), new Expression('NOW()')]
Вроде ты делал хелпер для sql конструкций таких?

2024-10-01 21:30 UTC, supermetrolog commented on migrations/m240930_162744_create_user_access_token_table.php
> +			'expires_at'   => $this->timestamp()->notNull(),
Тут составной индекс нужен

2024-10-01 21:30 UTC, supermetrolog commented on models/ActiveQuery/UserQuery.php
> +	public function byAccessToken(string $token): self
Название метода не соответствует тому что она делает 
По идее она должна фильтровать, но она просто джойнит

2024-10-01 21:30 UTC, supermetrolog commented on models/ActiveQuery/UserQuery.php
> +		return $this->leftJoin(['uat' => $userAccessToken], ['uat.user_id' => $this->field('id')]);
Подзапросы так себе всегда работают 
С ними можно мудрить при оптимизациях либо если по другому не получается 
Плюс вместо низкоуровнего джойна здесь можно использовать joinWith по связи

Когда пишешь связь можно вместо строки пробросить так [relName => fn $query UserAccessTokenQuery]

Плюс нужно указать тип джойна inner join 
Потому что сейчас этот метод по идее не работает так как не фильтрует ничего

2024-10-01 21:30 UTC, supermetrolog commented on models/UserAccessToken.php
> +	}
Чтобы такие штуки сюда не писать у нас есть отдельный query класс 
Это все нужно писать там, а модель оставить чистой

2024-10-01 21:30 UTC, supermetrolog commented on models/forms/User/UserForm.php
> +			self::SCENARIO_CREATE => [...$common, 'username', 'password', 'email_password',],
А password и email_password мы обновить не можем?

2024-10-01 21:30 UTC, supermetrolog commented on resources/Authentication/AuthenticationLoginResource.php
> +class AuthenticationLoginResource extends JsonResource
Нейминг

2024-10-01 21:30 UTC, supermetrolog commented on usecases/Authentication/AuthenticationService.php
> +		$userAgent = Yii::$app->request->getUserAgent();
Сервис ничего не должен знать о реквестах 
Плюс yii::app лучше не использовать
Если нужен security его можно прокинуть в конструкторе

2024-10-01 21:30 UTC, supermetrolog commented on usecases/Authentication/AuthenticationService.php
> +		}
SaveOrThrow есть

2024-10-01 21:30 UTC, supermetrolog commented on usecases/Authentication/AuthenticationService.php
> +			throw new Exception('Токен авторизации уже не является актуальным.');
Типизировать ошибку можно если она нужна снаружи

2024-10-01 21:30 UTC, supermetrolog commented on usecases/Authentication/AuthenticationService.php
> +			throw new Exception('Ошибка при генерации токена авторизации.');
Типизировать можно если нужна такая ошибка снаружи

2024-10-01 21:30 UTC, supermetrolog commented on usecases/Authentication/AuthenticationService.php
> +	public function authenticate(string $username, string $password): AuthenticationResponseDto
Нейминг

2024-10-01 21:30 UTC, supermetrolog commented on usecases/Authentication/AuthenticationService.php
> +class AuthenticationService
Нейминг
Можно просто AuthService назвать 
Будет подразумевать и аутентификацию и авторизацию

2024-10-01 21:30 UTC, supermetrolog commented on usecases/Authentication/AuthenticationService.php
Комменты бессмысленны 

Без комментов все понятно, поэтому бесполезная трата времени 
Если без комментов не понятно значит это говнокод 
Конечно бывают ситуации, когда что-то действительно сложное надо описать, но это точно не этот случай

2024-10-01 21:30 UTC, supermetrolog commented on usecases/User/UserService.php
> +			$userId = $model->signUp();
Ну это булщит 
Но я так полагаю это в след рефакторинге уберется или как?

2024-10-02 05:14 UTC, nknwns commented on controllers/UserController.php
> +		$userProfileForm->phones = ArrayHelper::getValue($userProfileData, 'phones', []);
Можешь не поверить, но почему-то нет в load этих массивов, когда делаю просто через load. Иначе бы я такую херню не делал

2024-10-02 05:21 UTC, nknwns commented on controllers/UserController.php
> +			return AuthenticationLoginResource::make($authenticated)->toArray();
Переименовано

2024-10-02 05:22 UTC, nknwns commented on controllers/UserController.php
> +		$token = TokenHelper::parseBearerToken(Yii::$app->request->headers->get('Authorization'));
Упс, я хз почему так написал, исправлено

2024-10-02 09:35 UTC, nknwns commented on controllers/UserController.php
> +	}
Отрефачил

2024-10-02 09:35 UTC, nknwns commented on controllers/UserController.php
> +	}
Готово

2024-10-02 09:36 UTC, nknwns commented on dto/Authentication/AuthenticationResponseDto.php
> +class AuthenticationResponseDto extends BaseObject
Заменено на Auth

2024-10-02 09:54 UTC, nknwns commented on helpers/TokenHelper.php
> +		return $matches[1] ?? null;
Создано исключение, дропается если нет токена

2024-10-02 09:55 UTC, nknwns commented on migrations/m240930_162744_create_user_access_token_table.php
> +			'ip'           => $this->string(19),
Потому что я разучился умножать 4 на 3. Исправлено

2024-10-02 09:58 UTC, nknwns commented on migrations/m240930_162744_create_user_access_token_table.php
> +			'user_agent'   => $this->string(),
Я даже не подумал об этом.. Нагуглил, что существуют юзер агенты длинной 8010 символов....

2024-10-02 10:03 UTC, nknwns commented on migrations/m240930_162744_create_user_access_token_table.php
> +			'user_id'      => $this->integer()->notNull(),
Забыл добавить. Исправлено

2024-10-02 10:25 UTC, nknwns commented on models/ActiveQuery/UserQuery.php
> +	public function byAccessToken(string $token): self
Исправлено, тупанул

2024-10-02 10:44 UTC, nknwns commented on resources/Authentication/AuthenticationLoginResource.php
> +class AuthenticationLoginResource extends JsonResource
Исправлено

2024-10-02 10:45 UTC, nknwns commented on usecases/Authentication/AuthenticationService.php
> +class AuthenticationService
Исправлено

2024-10-02 12:39 UTC, nknwns commented on helpers/DateIntervalHelper.php
> +		return new DateInterval("P{$days}D");
Если ты про фигурные, то да
Undefined variable '$daysD'

2024-10-02 13:37 UTC, nknwns commented on usecases/User/UserService.php
> +			$userId = $model->signUp();
Это старый метод, у меня вчера просто сил не хватило еще и его переписать. Переделано.

2024-10-02 13:38 UTC, nknwns commented on usecases/Authentication/AuthenticationService.php
> +		$userAgent = Yii::$app->request->getUserAgent();
Исправлено

2024-10-02 13:38 UTC, nknwns commented on models/UserAccessToken.php
> +	}
Исправлено

2024-10-02 15:52 UTC, nknwns commented on dto/User/CreateUserProfileDto.php
> +	public ?int    $user_id;
Переделано

2024-10-02 16:24 UTC, nknwns commented on models/ActiveQuery/UserQuery.php
> +		return $this->leftJoin(['uat' => $userAccessToken], ['uat.user_id' => $this->field('id')]);
Да, переделал

2024-10-02 17:11 UTC, nknwns commented on models/forms/User/UserForm.php
> +			self::SCENARIO_CREATE => [...$common, 'username', 'password', 'email_password',],
Исправлено

2024-10-02 18:05 UTC, nknwns commented
1. Дропнул таблицу `auth_key`
2. Добавлено исключение `InvalidBearerTokenException`
3. Добавлен хелпер `beforeNow`, `afterNow` для работы "Дата после", "Дата до"
4. Добавлен хелпер `truncate` для усечения строки до определенной длины
5. `TokenHelper` теперь дропает новое исключение вместо `null`
6. Добавлен `ValidatorHelper` с методами `whenIsArray`, `whenIsNotArray` для удобства работы с конструкциями `when` в form rules
7. Добавлен `UserSearch` для поиска юзеров, есть возможность поиска по `search`, несколько сортировок
8. `SignUp` удален, легаси
9. `UserController` переведен на наш rest-контроллер
10. Добавлен `AuthUserAgentDto`
11. Отрефачены `User` и `UserProfile`
12. Созданы ресурсы для юзера контактными данными
13. И всякие мелкие исправления по типу изменения нейминга ли корректировки запросов (по тредам).

2024-10-02 19:06 UTC, supermetrolog requested changes

2024-10-02 19:06 UTC, supermetrolog commented on usecases/Auth/AuthService.php
> +		$userAccessToken = UserAccessToken::find()->notDeleted()->byToken($token)->one();
А почему просто в запросе valid не искать? И тогда не придется isValid проверять и нижний if просто исчезнет 

Можно просто return ...->exists()

2024-10-02 19:06 UTC, supermetrolog commented on usecases/Auth/AuthService.php
> +		}
Лучше писать так:

If !tokenIsValid
  throw exception

code...

2024-10-02 19:06 UTC, supermetrolog commented on models/UserProfile.php
> +	public static function createUserProfile($post_data, $uploadFileModel)
По моему это уже в сервис вынесено, нет?

2024-10-02 19:06 UTC, supermetrolog commented on usecases/User/UserService.php
> +			return User::find()->with('userProfile')->where(['id' => $model->id])->one();
Ну это булщит 
У тебя юзер уже есть, зачем лишний бесполезный запрос в базу делать?

2024-10-02 19:06 UTC, supermetrolog commented on usecases/User/UserService.php
Вообще здесь должна быть логика только с юзером связанная 
Чтобы создавать/обновлять сразу и юзера и его профиль можно сделать сервис, который будет оперировать сервисом юзера и профиля
UserWithProfileService например

2024-10-03 05:15 UTC, nknwns commented on helpers/TokenHelper.php
> +		}
Ну пока оставим так, потому что эта регулярка норм
А по поводу `startWith` - это же например просто чекает, начинается ли строка с `Bearer`. А в данном кейсе мне нужно не просто начинается, но и вытащить токен после этого `Bearer`

2024-10-03 05:43 UTC, nknwns commented on resources/User/UserWithContactsResource.php
> +class UserWithContactsResource extends JsonResource
Есть урлы, которые требуют получить юзеров с контактами в UserProfile
Я решил сделать для таких случаев отдельный ресурс, чтобы отдавать с контактами в нужных эндпоинтах (раньше там было в запросах expand всегда)

2024-10-03 06:09 UTC, nknwns commented on usecases/User/UserService.php
Ок, позже выделю в отдельный сервис для дальнейшней гибкости (таску создал, будет исполнена потом)

2024-10-03 06:10 UTC, nknwns commented on models/UserProfile.php
> +	public static function createUserProfile($post_data, $uploadFileModel)
Ага, я забыл чет почистить его. Только `User` почистил полностью. Давай тоже в след таске по рефакторингу все это вычищу, чтобы сейчас не добавлять тебе кода для проверки

2024-10-03 16:40 UTC, supermetrolog requested changes

2024-10-03 16:40 UTC, supermetrolog commented on controllers/UserController.php
> +		}
Так нельзя делать 
Во первых ты внутреннюю ошибку впихнул в ответ клиенту 
Там может хоть запрос к базе выплюнуться 
Во вторых ты ловишь Exception от которого все ошибки отнаследованы. Получается любая ошибка будет интерпретироваться как forbidden, что не является правдой

2024-10-03 16:40 UTC, supermetrolog commented on controllers/UserController.php
> +		if ($user === null || !$user->isAdministrator()) {
На null можно не проверять
Во первых у identity есть методы типа isGuest чтобы чекать есть юзер или нет 
Во вторых если этот экшен требует авторизации, то сюда мы попадем только если будет юзер, поэтому проверять это лишние действия

2024-10-03 16:40 UTC, supermetrolog commented on controllers/UserController.php
> +		}
Надо все таки rbac завести а то это выглядит стремно 

Тут ниче не делай, это в другой таске сделаем

2024-10-03 16:40 UTC, supermetrolog commented on controllers/UserController.php
> +		}
Бессмысленный код. Никогда не выполнится. Можно убрать

2024-10-03 16:40 UTC, supermetrolog commented on controllers/UserController.php
> +	 * @throws ModelNotFoundException
Подскажи плз в AppController перехватывается это исключение?

2024-10-03 16:40 UTC, supermetrolog commented on models/search/UserSearch.php
> +			$data->role = ArrayHelper::toArray($data->role);
Это работает вообще? data это же массив, а ты как к объекту обращаешься

2024-10-03 16:40 UTC, supermetrolog commented on usecases/Auth/AuthService.php
> +			throw new InvalidBearerTokenException();
Юзкейс не знает бирер токен это или еще какой 
Поэтому исключение другое нужно

2024-10-03 16:40 UTC, supermetrolog commented on usecases/Auth/AuthService.php
> +			throw new InvalidBearerTokenException();
Вообще не вижу смысла в этой валидации токена и в такой ошибке
Просто получаешь токен с oneOrThrow и усе.

2024-10-03 16:40 UTC, supermetrolog commented on usecases/Auth/AuthService.php
> +		$userAccessToken = UserAccessToken::find()->valid()->byToken($token)->oneOrThrow();
Ну вот тут ты делаешь тот же запрос что и при валидации
Поэтому как я выше писал это можно упростить

2024-10-03 16:51 UTC, nknwns commented on controllers/UserController.php
> +	 * @throws ModelNotFoundException
Да
```
} catch (ModelNotFoundException $e) {
	throw new NotFoundHttpException($e->getMessage(), $e->getCode(), $e);
}
```

2024-10-03 16:53 UTC, supermetrolog commented on controllers/UserController.php
> +	 * @throws ModelNotFoundException
Спасибо

2024-10-03 18:57 UTC, supermetrolog commented on helpers/DateIntervalHelper.php
> +		return new DateInterval("P{$days}D");
https://php-play.dev/?c=DwfgDgFmBQD0sAICmAPAhgWzAGyQgxgPYAmS00AJAG5oBOCAvAgIwBMAzANzlL4SEIARABckAZ2HU6gzkA&v=7.4&f=html

Не нужны по моему все-таки

2024-10-03 19:18 UTC, nknwns commented on helpers/TokenHelper.php
> +		}
Готово

2024-10-03 19:20 UTC, nknwns commented on usecases/Auth/AuthService.php
> +		$userAccessToken = UserAccessToken::find()->notDeleted()->byToken($token)->one();
Исправлено

2024-10-03 19:20 UTC, nknwns commented on controllers/UserController.php
> +		}
Исправлено

2024-10-03 19:21 UTC, nknwns commented on usecases/Auth/AuthService.php
> +		}
Исправлено

2024-10-03 19:26 UTC, nknwns commented on usecases/Auth/AuthService.php
> +			throw new InvalidBearerTokenException();
Исправлено

2024-10-03 19:26 UTC, nknwns commented on usecases/Auth/AuthService.php
> +		$userAccessToken = UserAccessToken::find()->valid()->byToken($token)->oneOrThrow();
Упрощено

2024-10-03 19:26 UTC, nknwns commented on models/search/UserSearch.php
> +			$data->role = ArrayHelper::toArray($data->role);
Исправлено

2024-10-03 19:36 UTC, supermetrolog approved these changes

2024-10-03 19:37 UTC, supermetrolog approved these changes

2024-10-03 19:37 UTC, merged