[#413] Manipulate user sessions
supermetrolog/crmka pull request #85
Opened 2024-10-06 19:49 UTC by nknwns

1. Добавлены урлы для работы с сессиями. У `/users` это `GET` `/users/:id/sessions` для списка всех сессий юзера и `DELETE` `/users/:id/sessions` для удаления всех сессий юзера. Отдельно создан эндпоинт `/sessions` для просмотра всех сессий всех пользователей и удаления конкретной сессии по `id`.
2. Создан `userAccessTokenService` для инкапсуляции логики работы с этой моделью.
3. Количество дней жизни токена увеличено до 30 (было 14).
4. При логине на клиент возвращается еще и `id` текущего токена (нужно для определения на странице "Безопасность", какой именно токен является текущим).
5. Если запрос на удаление всех токенов сотрудника прилетел от самого сотрудника, то удалятся все сессии кроме текущей. Если запрос прилетел от администратора, то удалятся абсолютно все активные токены юзера. (Логика проверки будет потом изменена с использованием RBAC)

2024-10-06 20:46 UTC, supermetrolog requested changes

2024-10-06 20:46 UTC, supermetrolog commented on controllers/SessionController.php
> +	public function actionIndex(): ActiveDataProvider
Сюда кто угодно может попасть? Получается любой чел может просто украсть токен другого чела и под ним залогиниться?

2024-10-06 20:46 UTC, supermetrolog commented on controllers/UserController.php
> +		$user  = $this->user->identity;
Не понятно что есть что. Название model ни о чем не говорит. А user должен быть вместо model, а вместо user должен быть currentUser ну или лучше просто identity

2024-10-06 20:46 UTC, supermetrolog commented on controllers/UserController.php
> +
Бизнес логика. Ее в сервис надо выносить

2024-10-06 20:46 UTC, supermetrolog commented on controllers/UserController.php
> +			$this->accessTokenService->deleteAllByUserId($model->id, [$userAccessToken->id]);
Я так полагаю, что второй параметр это except? В таком случае это уже не All. Название противоречит тому что происходит внутри

2024-10-06 20:46 UTC, supermetrolog commented on models/search/UserAccessTokenSearch.php
> +	public ?array $user_ids;
Не, в моделях нельзя типы указывать. Если послать в качестве id строку, у тебя сервис начнет пятисотить просто. До валидации дело не дойдет.

2024-10-06 20:46 UTC, supermetrolog commented on usecases/User/UserAccessTokenService.php
> +			$models = UserAccessToken::find()->valid()->byUserId($userId)->andWhere(['not in', 'id', $excludeIds])->all();
Спускай плз цепочку по строкам если она длинная 
Плюс для not in можно сделать метод andWhereNotIn() 
В ядро можно занести. Возможно уже есть такое.

2024-10-07 02:16 UTC, nknwns commented on usecases/User/UserAccessTokenService.php
> +			$models = UserAccessToken::find()->valid()->byUserId($userId)->andWhere(['not in', 'id', $excludeIds])->all();
Упс, такое ты уже делал. Исправлено

2024-10-07 02:16 UTC, nknwns commented on models/search/UserAccessTokenSearch.php
> +	public ?array $user_ids;
Исправлено

2024-10-07 02:27 UTC, nknwns commented on controllers/SessionController.php
> +	public function actionIndex(): ActiveDataProvider
1. Не подумал чет, что лучше его закрыть для всех обычных юзеров
2. Эндпоинт не отдает сами токены ни в коем случае, только информацию о них. Ипшник, юзер агент, дату истечения. Но сам токен получить через запрос никак не получится

Добавил проверку на роли

2024-10-07 02:28 UTC, nknwns commented on controllers/UserController.php
> +		$user  = $this->user->identity;
Исправлено

2024-10-07 03:11 UTC, nknwns commented on controllers/UserController.php
> +
Исправлено

2024-10-07 03:11 UTC, nknwns commented on controllers/UserController.php
> +			$this->accessTokenService->deleteAllByUserId($model->id, [$userAccessToken->id]);
Исправлено

2024-10-07 06:01 UTC, nknwns commented
![](https://github.trello.services/images/mini-trello-icon.png) [Просмотр сессий и разлогин](https://trello.com/c/qfIT4CnK/413-%D0%BF%D1%80%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80-%D1%81%D0%B5%D1%81%D1%81%D0%B8%D0%B9-%D0%B8-%D1%80%D0%B0%D0%B7%D0%BB%D0%BE%D0%B3%D0%B8%D0%BD)

2024-10-07 07:04 UTC, supermetrolog requested changes

2024-10-07 07:04 UTC, supermetrolog commented on resources/User/UserProfileResource.php
> +		return $fullName;
Можно вынести в string helper 
Метод join сделать, который принимает бесконечное колво строк и джойнит их в одну

2024-10-07 07:04 UTC, supermetrolog commented on resources/User/UserProfileResource.php
> +		return StringHelper::trim($shortName);
Тоже можно упростить с хелпером

2024-10-07 07:04 UTC, supermetrolog commented on resources/User/UserProfileResource.php
> +		return StringHelper::trim($this->resource->first_name . " " . $this->resource->middle_name);
Тоже можно

2024-10-07 07:31 UTC, nknwns commented on controllers/UserController.php
> +		$user  = $this->user->identity;
Готово

2024-10-07 07:32 UTC, nknwns commented on helpers/StringHelper.php
> +	public static function toUpperCase(string $string): string
Исправлено

2024-10-07 07:33 UTC, nknwns commented on models/User.php
> +	public function isDirector(): bool
Исправлено

2024-10-07 08:12 UTC, nknwns commented on resources/User/UserProfileResource.php
> +		return $fullName;
Готово

2024-10-07 08:16 UTC, nknwns commented on resources/User/UserProfileResource.php
> +		return StringHelper::trim($this->resource->first_name . " " . $this->resource->middle_name);
Готово

2024-10-07 16:51 UTC, supermetrolog requested changes

2024-10-07 16:51 UTC, supermetrolog commented on helpers/StringHelper.php
> +		$notEmptyStrings = ArrayHelper::filter(ArrayHelper::toArray($strings), fn($str) => self::notEmpty($str));
toArray разве нужен? По идее там всегда array

2024-10-07 16:51 UTC, supermetrolog commented on resources/User/UserProfileResource.php
> +	}
Эти методы лучше вынести в UserProfile, они прям созданы для модели и можно потом с кайфом переиспользовать

2024-10-07 18:36 UTC, nknwns commented on resources/User/UserProfileResource.php
> +	}
Они там и были (в старом варианте, без хелперов), но я почему-то подумал, что создание fullName, shortName и mediumName это задача ресурса (ведь он выводит нужный нам формат данных для того чтобы отдать клиенту, а значит он и данные может вот так преобразовывать).
Убрал из ресерса и обновил вариант в моделе

2024-10-07 18:39 UTC, supermetrolog approved these changes

2024-10-07 18:42 UTC, supermetrolog approved these changes

2024-10-07 18:42 UTC, merged