Refactor company module
supermetrolog/crmka pull request #99
Opened 2024-10-24 20:23 UTC by nknwns

2024-10-26 14:53 UTC, supermetrolog requested changes

2024-10-26 14:53 UTC, supermetrolog commented on models/Contact.php
> +		return StringHelper::isNotEmpty($fullName) ? $fullName : null;
По моему тут можно очень просто написать $fullName ?: null

2024-10-26 14:53 UTC, supermetrolog commented on models/Contact.php
> +		return StringHelper::isNotEmpty($shortName) ? $shortName : null;
$shortName ?: null

2024-10-26 14:53 UTC, supermetrolog commented on models/Contact.php
> +				$fs->last_name ?? ""
Не пойму. Тут ничего не возвращается?

2024-10-26 14:53 UTC, supermetrolog commented on models/Contact.php
> +				$fs->last_name ?? ""
Плюс это тоже можно в геттер вынести

2024-10-26 14:53 UTC, supermetrolog commented on models/Contact.php
> +				return Phone::isValidPhoneNumber($phone['phone']);
Тут точно 'phone'? В старом коде было 'nativePhone'

2024-10-26 14:53 UTC, supermetrolog commented on models/Contact.php
> +				return !Phone::isValidPhoneNumber($phone['phone']);
Тоже было nativePhone

2024-10-26 14:53 UTC, supermetrolog commented on models/Media.php
> +		}
Не пойму зачем все это?

2024-10-26 14:53 UTC, supermetrolog commented on helpers/DateTimeHelper.php
> +	}
Тут захардкожен формат, что не удобно
Здесь бы возвращать DateTimeInterface
Будет гораздо гибче

А если нужно форматировать сразу, то по аналогии с makef сделать новый метод

2024-10-26 14:53 UTC, supermetrolog commented on models/Request.php
> +		$fields['format_name'] = fn() => $this->getFormatName();
О, я думал стрелочные функции только в php 8 завезли)

2024-10-26 14:53 UTC, supermetrolog commented on models/forms/Contact/ContactCommentForm.php
> +			[['author_id', 'contact_id'], 'integer'],
Автора тоже на exist чекнуть надо

2024-10-26 14:53 UTC, supermetrolog commented on models/miniModels/CompanyFile.php
От этого класса и таблицы нужно отказаться 
У нас же теперь все в медиа лежит

2024-10-26 14:53 UTC, supermetrolog commented on models/miniModels/Phone.php
> +	}
Можно сделать валидатор отдельный для этого
Но можешь забить это я на будущее

2024-10-26 14:53 UTC, supermetrolog commented on resources/Company/CompanyInListResource.php
> +		return $this->resource->logo->src ?? null;
Если null, вернуть null?
Будто в этой функции нет необходимости и можно просто src подставить и усе

2024-10-26 14:53 UTC, supermetrolog commented on resources/Company/CompanyViewResource.php
> +		return $this->resource->logo->src ?? null;
Писал выше

2024-10-26 14:53 UTC, supermetrolog commented on usecases/Company/CompanyFileService.php
> +			$path = "$name.{$dto->file->extension}";
Ну че то мне это совсем не нравится
Мы делали медиа компонент чтобы такие операции инкапсулировать в нем
Может все это сделать компонент и вернуть результат с готовыми данными, а мы уже оттуда и узнаем какой там email и path

Ну и от CompanyFile нужно отказываться вообще

2024-10-26 14:53 UTC, supermetrolog commented on usecases/Company/CompanyGeneralContactService.php
> +	}
Это супер странно
Не знаю как это используется, но думаю можно не делать так

Ну хотя бы deleteByCompanyID нужно назвать и получать эту айдишку

2024-10-26 14:53 UTC, supermetrolog commented on usecases/Company/CompanyGeneralContactService.php
> +	public function create(Company $company, CompanyContactsDto $contactsDto): Contact
Почему бы company_id просто не сунуть в DTO?

2024-10-26 14:53 UTC, supermetrolog commented on usecases/Company/CompanyService.php
> +			}
Ну раз ошибка пусть эксепшен дальше летит и отменяет транзацию
Зачем его ловить тут?

2024-10-26 14:53 UTC, supermetrolog commented on usecases/Company/CompanyService.php
> +			}
Тут приходится прыгать между абстракциями
Тут сначала пишем высокоуровневый код, потом переходим к низкоровневой работе с массивом и поиском разницы
Такой код не читабелен
Нужно скрывать такие штуки в отдельных методах

Например, можно сделать метод this->deleteMissingFiles и скрыть там эту логику

2024-10-26 14:53 UTC, supermetrolog commented on usecases/Company/CompanyService.php
> +			}
this->saveFiles()

2024-10-26 14:53 UTC, supermetrolog commented on usecases/Company/CompanyService.php
> +				]));
this->saveLogo()

2024-10-26 14:53 UTC, supermetrolog commented on usecases/Company/CompanyService.php
> +			}
Увидел что мы уже закоммитили, но не понимаю зачем
Нужно делать это внутри транзакции иначе потом будут проблемы с данными

2024-10-26 14:53 UTC, supermetrolog commented on usecases/Company/CompanyService.php
> +			}
Ниже писал
this->saveFiles()

2024-10-26 14:53 UTC, supermetrolog commented on usecases/Company/CompanyService.php
> +				]));
Ниже писал
this->saveLogo

2024-10-26 14:53 UTC, supermetrolog commented on usecases/Company/CompanyService.php
> +			}
Тоже внутри транзакции вызывать и не глушить исключения

2024-10-26 15:24 UTC, nknwns commented on behaviors/CreateManyMiniModelsBehaviors.php
Конечно нужно. Я об этом коммент написал с TODO. Но сейчас это не так быстро сделать. Там еще некоторые модели на этом работают и нужно будет сделать для каждой из них сервисы и внедрить их в сервисы основных моделей

2024-10-26 15:26 UTC, nknwns commented on components/Media/Media.php
> +			$this->baseUrl = Yii::$app->request->hostInfo . $this->baseFolder;
Не понял(

2024-10-26 16:19 UTC, nknwns commented on models/CompanySearch.php
> +			$data['dateStart'] = $data['dateStart'] ?? DateTimeHelper::makef('01.01.1970', 'Y-m-d');
Из старого кода. Не придумал сходу как поменять. Да и в принципе search переписать бы немного

2024-10-27 11:41 UTC, nknwns commented on models/Contact.php
> +				return Phone::isValidPhoneNumber($phone['phone']);
В старом коде этот `native_phone` сверху вычислялся. То есть этого `native_phone` в принципе не существует. Если посмотреть старый код, то `native_phone` это `phone` из таблицы, а `phone` это уже transformed `native_phone` (=== trasformed `phone`). Поэтому я его тут просто убрал, он описан в ресурсе.

Сюда уже можно не добавлять, вроде в фронте в других урлах (в которых еще нет ресурсов) он не используется. В принципе от этих ef и f избавимся позже

2024-10-27 11:41 UTC, nknwns commented on models/Contact.php
> +				return !Phone::isValidPhoneNumber($phone['phone']);
Уже ответил по этому поводу

2024-10-27 11:42 UTC, nknwns commented on helpers/DateTimeHelper.php
> +	}
Шота я заработался и даже не передал формат хотя бы аргументом вторым, упс..

2024-10-27 11:43 UTC, nknwns commented on models/Request.php
> +		$fields['format_name'] = fn() => $this->getFormatName();
С 7.4 написано в доке. Ты же не против их? Просто удобно и лаконично для подобных штук.

2024-10-27 14:50 UTC, nknwns commented on models/miniModels/CompanyFile.php
Давай создам таску на это и потом сделаю, ок?

2024-10-27 17:28 UTC, nknwns commented on usecases/Company/CompanyFileService.php
> +			$path = "$name.{$dto->file->extension}";
Ну это нужно перетащить все файлы на медиа, тогда этого сервиса в принципе не будет существовать. Будет просто createMediaService юзаться. На потом таска

2024-10-27 19:42 UTC, supermetrolog requested changes

2024-10-27 19:42 UTC, supermetrolog commented on components/Media/Media.php
> +	public string $baseUrl;
Нужно сделать приватными

2024-10-27 19:42 UTC, supermetrolog commented on components/Media/Media.php
> +//		return StringHelper::join(StringHelper::SYMBOL_SLASH, $this->baseUrl, $filePath);
Комментик лишний

2024-10-27 19:42 UTC, supermetrolog commented on models/CompanySearch.php
> +			$data['dateStart'] = $data['dateStart'] ?? DateTimeHelper::makef('01.01.1970', 'Y-m-d');
Можно оставить его null
И заменить between на два фильтра >= и <=

2024-10-27 19:42 UTC, supermetrolog commented on models/forms/Company/CompanyContactsForm.php
> +	}
Ну это странная штука 
Можно через each валидатор провалидировать элементы массива

2024-10-27 19:42 UTC, supermetrolog commented on models/forms/Company/CompanyMiniModelsForm.php
> +	}
Писал выше. Можно реализовать штатным способом

2024-10-27 19:42 UTC, supermetrolog commented on resources/Company/CompanyInListResource.php
> +	private function getLogo(): ?string
Используется несколько раз 
Можно сделать геттер в модели и переиспользовать

2024-10-27 19:42 UTC, supermetrolog commented on resources/Company/CompanyViewResource.php
> +	public function getLogo(): ?string
Геттер в модели

2024-10-27 19:42 UTC, supermetrolog commented on usecases/Company/CompanyService.php
> +//			);
А че закомментил?

2024-10-27 19:42 UTC, supermetrolog commented on usecases/Company/CompanyService.php
> +			if ($logoShouldBeDeleted && $model->logo) {
Ну вот ты вынес часть условия в эту переменную, но почему-то еще одно условие написал тут отдельно. Его можно тоже вынести и тут чекать только одно значение

2024-10-27 19:42 UTC, supermetrolog commented on usecases/Company/CompanyWithGeneralContactService.php
> +			$contact = Contact::find()->byCompanyId($company->id)->general()->one();
К этому можно через связь обратиться 
Сделать типа getGeneralContact

И выше там был вроде такой же запрос при удалении в сервисе

2024-10-27 19:43 UTC, supermetrolog commented on behaviors/CreateManyMiniModelsBehaviors.php
Ок, ладно
В след раз можно будет

2024-10-27 19:50 UTC, supermetrolog commented on models/Request.php
> +		$fields['format_name'] = fn() => $this->getFormatName();
Я только ЗА

2024-10-27 19:50 UTC, supermetrolog commented on models/miniModels/CompanyFile.php
Да, давай 👍

2024-10-27 20:06 UTC, nknwns commented on usecases/Company/CompanyService.php
> +//			);
Упс

2024-10-27 21:33 UTC, supermetrolog approved these changes

2024-10-27 21:34 UTC, merged